spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        current_session_context_class: thread
    open-in-view: false

logging:
  file:
    name: RentCarGradle.log
    path: /
  level:
    root: INFO
    org:
      springframework:
        jdbc:
          core: TRACE